/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.student.information.view;

import com.student.information.domain.TelecommunictionDpt;
import com.student.information.service.TelecommunictionDptService;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author anik
 */
public class TelecommunictionDptList extends javax.swing.JFrame {

    /**
     * Creates new form TelecommunictionDptList
     */
    public TelecommunictionDptList() {
        initComponents();
        refreshTable();
        this.setTitle("Telecommunication Department");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowCurrentInformation = new javax.swing.JTable();
        lblShowTableHadder = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        tblShowCurrentInformation.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        tblShowCurrentInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student ID", "First Name", "Sur Name", "Date of birth", "Gender", "Email", "Number", "Preasent Address", "Permanent Address", "House No", "Post Code", "Dpt Code"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShowCurrentInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblShowCurrentInformation.setFillsViewportHeight(true);
        tblShowCurrentInformation.setRowHeight(30);
        tblShowCurrentInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowCurrentInformationMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblShowCurrentInformation);

        lblShowTableHadder.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        lblShowTableHadder.setForeground(new java.awt.Color(102, 102, 102));
        lblShowTableHadder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowTableHadder.setText("Electrical Department All Student List");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Refresh");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowTableHadder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblShowTableHadder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblShowCurrentInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowCurrentInformationMouseClicked
        // TODO add your handling code here:
        
        ShowStudent showStudent = new ShowStudent(); // Create shiwStudent frame object
        TelecommunictionDptService telecommunictionDptService = new TelecommunictionDptService(); // create telecommunication department sercice object

        showStudent.setTitle("Telecommunication Department"); // set Title in showStudent frame
        
        // get selected row
        int row = tblShowCurrentInformation.getSelectedRow();
        // get Table model
        TableModel model = tblShowCurrentInformation.getModel();

        // get image , byte arry formate from database
        byte[] image = telecommunictionDptService.getImage(Integer.parseInt(model.getValueAt(row, 1).toString()));
        
        if (image != null) {
            showStudent.lblShowImage.setIcon(new ImageIcon(image)); // set image in lable , help ImageIcon
        } else {
            showStudent.lblShowImage.setText("No Iamge available");
        }
        
        showStudent.lblStudentId.setText(model.getValueAt(row, 1).toString()); // set student id in lable
        showStudent.lblFirstName.setText(model.getValueAt(row, 2).toString()); // set first name in lable
        showStudent.lblDateOfBirth.setText(model.getValueAt(row, 4).toString()); // set date of birth in lable
        showStudent.lblGander.setText(model.getValueAt(row, 5).toString()); // set gander in lable
        showStudent.lblEmail.setText(model.getValueAt(row, 6).toString()); // set email in lable
        showStudent.lblMobileNumber.setText(model.getValueAt(row, 7).toString()); // ser mobile number in lable
        
        showStudent.setVisible(true); // set visible true [ showStudent frame ]
        
    }//GEN-LAST:event_tblShowCurrentInformationMouseClicked

    /**
     * < telecommunictionDptDesplayInTable() >
     * this method show all [ Telecommunication department student information ]
     * in table.
     */
    public void telecommunictionDptDesplayInTable() {
        
        lblShowTableHadder.setText(null);
        lblShowTableHadder.setText("Telecommuniction Depertment All Student List");
        
        TelecommunictionDptService telecommunictionDptService = new TelecommunictionDptService();
        
        List<TelecommunictionDpt> getList = telecommunictionDptService.getRecordList();
        
        DefaultTableModel model = (DefaultTableModel) tblShowCurrentInformation.getModel();
        Object[] row = new Object[13];
        
        for (int i = 0; i < getList.size(); i++) {
            
            row[0] = getList.get(i).getId();
            row[1] = getList.get(i).getStudent_id();
            row[2] = getList.get(i).getStudent_fst_name();
            row[3] = getList.get(i).getStudent_sur_name();
            row[4] = getList.get(i).getDate_of_birth();
            row[5] = getList.get(i).getGander();
            row[6] = getList.get(i).getEmail();
            row[7] = getList.get(i).getNumber();
            row[8] = getList.get(i).getPresent_address();
            row[9] = getList.get(i).getPermanent_address();
            row[10] = getList.get(i).getHouse_no();
            row[11] = getList.get(i).getPost_code();
            row[12] = getList.get(i).getDpt_code();
            
            model.addRow(row);
        }
        
    }

    /**
     * < refreshTable >
     * this method clear only table.
     */
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblShowCurrentInformation.getModel();
        model.setRowCount(0);
        telecommunictionDptDesplayInTable();
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblShowTableHadder;
    private javax.swing.JTable tblShowCurrentInformation;
    // End of variables declaration//GEN-END:variables
}
